name: Notify chapter

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: dawidd6/action-download-artifact@v2
      with:
        if_no_artifact_found: warn
        name: known-chapters

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - run: bun install

    - run: bun run index.ts
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        CHAPTERS_URL: ${{ vars.CHAPTERS_URL }}
        CHAPTER_URL_ORIGIN: ${{ vars.CHAPTER_URL_ORIGIN }}

    - uses: actions/upload-artifact@v3
      with:
        path: known-chapters.json
        name: known-chapters
